@startuml

left to right direction
skinparam backgroundcolor oldlace

title Player Summary

rectangle Player #RoyalBlue;text:white
rectangle RenderersFamily #MediumSlateBlue;text:white
rectangle Views #FireBrick;text:white

note as N1
    Views don't know how to render anything.
    That's the Renderers's task.
end note

Player ..> Views : "Interacts"
Player --> RenderersFamily : Uses
RenderersFamily --> Views : Creates



'RenderersFamily  .[hidden] N1

@enduml